name: tugas_akhir
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^3.1.6
  cross_file: ^0.3.2
  cupertino_icons: ^1.0.4
  email_validator: ^1.0.4
  equatable: ^2.0.3
  firebase_auth: ^3.3.5
  firebase_database: ^9.0.5
  firebase_storage: ^10.2.5
  flushbar: ^1.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_icons: ^1.1.0
  flutter_image_compress: ^1.1.0
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.2.0
  http: ^0.13.3
  image_picker: ^0.8.3+1
  material_design_icons_flutter: ^5.0.6595
  provider: ^6.0.2
  shadow: ^1.0.0
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
  adaptive_icon_background: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/btn_add_photo.png
    - assets/btn_del_photo.png
    - assets/user_pic.png
    - assets/labels.txt
    - assets/model_unquant.tflite
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
