import 'dart:io';

import 'package:tugas_akhir/bloc/blocs.dart';
import 'package:tugas_akhir/models/models.dart';
import 'package:tugas_akhir/services/services.dart';
import 'package:tugas_akhir/shared/shared.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:email_validator/email_validator.dart';
import 'package:firebase_auth/firebase_auth.dart' as auth;
import 'package:flushbar/flushbar.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:provider/provider.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart';
import 'package:bottom_navy_bar/bottom_navy_bar.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:tflite/tflite.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

part 'sign_in_page.dart';
part 'main_page.dart';
part 'wrapper.dart';
part 'splash_page.dart';
part 'account_confirmation_page.dart';
part 'identification_page.dart';
part 'article_page.dart';
part 'profile_page.dart';
part 'sign_up_page.dart';
part 'tambah_dataset_page.dart';
part 'edit_profile_pages.dart';
